name: Continuous Delivery

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: windows-latest
        strategy:
            matrix:
                architecture: ["x86", "x64"]

        steps:
            - uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.6"
                  architecture: ${{ matrix.architecture }}

            - name: Install pyinstaller
              run: python -m pip install pyinstaller

            - name: Build package to one directory
              run: |
                  python -m PyInstaller -w -D --clean -y --distpath dist-dir nxDumpMerger.py
                  cd dist-dir
                  powershell Compress-Archive nxDumpMerger ..\nxDumpMerger_Windows_${{ matrix.architecture }}.zip

            - name: Build package to one file
              run: |
                  python -m PyInstaller -w -F --clean -y --distpath dist-file nxDumpMerger.py
                  cd dist-file
                  move nxDumpMerger.exe ..\nxDumpMerger_Windows_${{ matrix.architecture }}.exe

            - name: Get the tag version
              id: get_version
              run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
              shell: bash

            - name: Create release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ steps.get_version.outputs.VERSION }}
                  release_name: ${{ steps.get_version.outputs.VERSION }}
                  draft: false
                  prerelease: false

            - name: Upload release asset (python script)
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: nxDumpMerger.py
                  asset_name: nxDumpMerger.py
                  asset_content_type: text/x-python

            - name: Upload release asset (builded dir)
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: nxDumpMerger_Windows_${{ matrix.architecture }}.zip
                  asset_name: nxDumpMerger_Windows_${{ matrix.architecture }}.zip
                  asset_content_type: application/zip

            - name: Upload release asset (builded one file)
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: nxDumpMerger_Windows_${{ matrix.architecture }}.exe
                  asset_name: nxDumpMerger_Windows_${{ matrix.architecture }}.exe
                  asset_content_type: application/x-dosexec
