name: Continuous Delivery

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: windows-latest
        strategy:
            matrix:
                architecture: ["x86", "x64"]

        steps:
            - uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.6"
                  architecture: ${{ matrix.architecture }}

            - name: Install pyinstaller
              run: python -m pip install pyinstaller

            - name: Build package to one directory
              run: |
                  python -m PyInstaller -w -D --clean -y --distpath dist-dir nxDumpMerger.py
                  cd dist-dir
                  powershell Compress-Archive nxDumpMerger ..\nxDumpMerger_Windows_${{ matrix.architecture }}.zip

            - name: Build package to one file
              run: |
                  python -m PyInstaller -w -F --clean -y --distpath dist-file nxDumpMerger.py
                  cd dist-file
                  move nxDumpMerger.exe ..\nxDumpMerger_Windows_${{ matrix.architecture }}.exe

            - name: Upload artifact (one dir)
              uses: actions/upload-artifact@v2
              with:
                  name: uploads
                  path: nxDumpMerger_Windows_${{ matrix.architecture }}.zip

            - name: Upload artifact (one file)
              uses: actions/upload-artifact@v2
              with:
                  name: uploads
                  path: nxDumpMerger_Windows_${{ matrix.architecture }}.exe
